---
services:
  qbittorrent:
    image: linuxserver/qbittorrent:${QBITTORRENT_VERSION:-latest}
    # example

  qbit_manage:
    image: ghcr.io/stuffanthings/qbit_manage:latest
    # example

  qbittorrent-qbitmanage-updater:
    container_name: qbittorrent-qbitmanage-updater
    # build: .
    image: ghcr.io/iamasink/qbittorrent-qbitmanage-updater:main
    environment:
      - QBITMANAGE_BRANCH=master     # optional, defaults to master
    volumes:
      - ./.env:/.env:rw              # mount .env file. ensure the file exists before starting this container, or it'll create a directory (invalid)
      # defaults to beside the docker-compose.yml
    restart: "no"